"""
app.py
------
Streamlit dashboard for the Bedrock Guardrail Graph Optimizer.

Run with:
    streamlit run src/app.py

This dashboard visualizes a GRAPH workflow optimizer: workflow graphs,
graph-path-aware redundant-check detection, and per-step optimizer
decisions -- not a flat row-filtering tool. Nothing here calls live Amazon
Bedrock Guardrails; all data is generated by the synthetic simulator in
this repo (see run_pipeline.py).
"""

from __future__ import annotations

import json
import os

import pandas as pd
import streamlit as st

try:
    import networkx as nx
    import matplotlib.pyplot as plt

    _HAS_VIZ = True
except ImportError:  # pragma: no cover
    _HAS_VIZ = False

st.set_page_config(page_title="Bedrock Guardrail Graph Optimizer", layout="wide")

OUTPUTS = "outputs"
DATA = "data"


@st.cache_data
def load_csv(name: str) -> pd.DataFrame:
    path = os.path.join(OUTPUTS, name)
    if not os.path.exists(path):
        return pd.DataFrame()
    return pd.read_csv(path)


@st.cache_data
def load_json(name: str) -> dict:
    path = os.path.join(OUTPUTS, name)
    if not os.path.exists(path):
        return {}
    with open(path, "r") as f:
        return json.load(f)


@st.cache_data
def load_traces() -> pd.DataFrame:
    path = os.path.join(DATA, "synthetic_workflow_traces.csv")
    if not os.path.exists(path):
        return pd.DataFrame()
    return pd.read_csv(path)


st.title("Bedrock Guardrail Graph Optimizer")
st.caption(
    "A graph-based orchestration prototype for Bedrock-style multi-agent workflows that reduces "
    "redundant guardrail checks while preserving trust-boundary safety coverage."
)
st.info(
    "This is a simulation. It does not connect to live Amazon Bedrock Guardrails or AgentCore "
    "Policy APIs. All numbers below come from synthetic workflow traces generated by this repo."
)

metrics = load_json("guardrail_metrics.json")
plan_df = load_csv("optimized_guardrail_plan.csv")
redundant_df = load_csv("redundant_paths.csv")
nodes_df = load_csv("graph_nodes.csv")
edges_df = load_csv("graph_edges.csv")
summary_df = load_csv("workflow_graph_summary.csv")
boundary_df = load_csv("boundary_coverage_matrix.csv")
explanations = load_json("guardrail_explanations.json")
traces_df = load_traces()

if not metrics or plan_df.empty:
    st.warning(
        "No pipeline output found yet. Run `python src/run_pipeline.py` from the project root to "
        "generate data, then reload this dashboard."
    )
    st.stop()

tabs = st.tabs(
    [
        "Overview",
        "Workflow Graph Explorer",
        "Redundant Path Analysis",
        "Optimized Guardrail Plan",
        "Boundary Coverage Matrix",
        "Graph Risk Summary",
        "Explanation Cards",
    ]
)

# ---------------------------------------------------------------------------
# 1. Overview
# ---------------------------------------------------------------------------
with tabs[0]:
    overall = metrics["overall"]
    safety = metrics["safety"]
    graph_m = metrics["graph"]

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Workflows analyzed", f"{graph_m['workflows_analyzed']:,}")
    c2.metric("Original guardrail calls", f"{overall['original_guardrail_calls']:,}")
    c3.metric("Optimized guardrail calls", f"{overall['optimized_guardrail_calls']:,}")
    c4.metric("Call reduction", f"{overall['guardrail_call_reduction_percent']}%")

    c5, c6, c7, c8 = st.columns(4)
    c5.metric("Latency saved", f"{overall['latency_saved_percent']}%")
    c6.metric("Cost saved", f"{overall['cost_saved_percent']}%")
    c7.metric("Boundary coverage preserved", f"{safety['boundary_coverage_preserved_percent']}%")
    c8.metric("High-risk checks preserved", f"{safety['high_risk_preservation_percent']}%")

    st.markdown("---")
    st.subheader("What makes this a graph workflow optimizer")
    st.markdown(
        "- Redundancy is detected by walking **UserInput -> FinalAnswer paths** through a directed graph, "
        "not by comparing arbitrary rows.\n"
        "- Every recommendation records the trust boundary it crosses and the graph path it belongs to.\n"
        "- Protected trust boundaries (`USER_TO_AGENT`, `AGENT_TO_TOOL`, `TOOL_TO_AGENT`, "
        "`AGENT_TO_FINAL_RESPONSE`) are always kept -- verified at 100% coverage below."
    )

# ---------------------------------------------------------------------------
# 2. Workflow Graph Explorer
# ---------------------------------------------------------------------------
with tabs[1]:
    st.subheader("Workflow Graph Explorer")
    workflow_ids = sorted(nodes_df["workflow_id"].unique()) if not nodes_df.empty else []
    if workflow_ids:
        selected_wf = st.selectbox(
            "Select a workflow_id", workflow_ids, key="workflow_graph_workflow_id_select"
        )

        wf_nodes = nodes_df[nodes_df["workflow_id"] == selected_wf]
        wf_edges = edges_df[edges_df["workflow_id"] == selected_wf]
        wf_plan = plan_df[plan_df["workflow_id"] == selected_wf]

        col_a, col_b = st.columns(2)
        with col_a:
            st.markdown("**Graph nodes**")
            st.dataframe(wf_nodes, use_container_width=True, height=220)
        with col_b:
            st.markdown("**Graph edges**")
            st.dataframe(wf_edges, use_container_width=True, height=220)

        st.markdown("**Ordered path view**")
        if not wf_edges.empty:
            try:
                path_str = " -> ".join(
                    pd.unique(wf_edges[["source_node", "target_node"]].values.ravel("K"))
                )
                st.code(path_str)
            except Exception:
                pass

        if _HAS_VIZ and not wf_edges.empty:
            st.markdown("**Directed graph render**")
            g = nx.DiGraph()
            for _, row in wf_edges.iterrows():
                g.add_edge(row["source_node"], row["target_node"], boundary=row["trust_boundary"])
            fig, ax = plt.subplots(figsize=(7, 4))
            pos = nx.spring_layout(g, seed=42)
            protected_edges = [
                (u, v) for u, v, d in g.edges(data=True)
                if d["boundary"] in ("USER_TO_AGENT", "AGENT_TO_TOOL", "TOOL_TO_AGENT", "AGENT_TO_FINAL_RESPONSE")
            ]
            internal_edges = [(u, v) for u, v in g.edges() if (u, v) not in protected_edges]
            nx.draw_networkx_nodes(g, pos, ax=ax, node_color="#e8eef7", node_size=1400, edgecolors="#2b4c7e")
            nx.draw_networkx_labels(g, pos, ax=ax, font_size=8)
            nx.draw_networkx_edges(g, pos, ax=ax, edgelist=protected_edges, edge_color="#2b4c7e", width=2)
            nx.draw_networkx_edges(
                g, pos, ax=ax, edgelist=internal_edges, edge_color="#999999", style="dashed", width=1.5
            )
            ax.set_axis_off()
            st.pyplot(fig)
            st.caption("Solid blue = protected trust boundary. Dashed gray = optimizable internal handoff.")

        st.markdown("**Per-step guardrail checks and recommended decisions**")
        st.dataframe(
            wf_plan[
                [
                    "step_id",
                    "source_node",
                    "target_node",
                    "trust_boundary",
                    "guardrail_type",
                    "risk_level",
                    "recommended_decision",
                    "reason",
                    "audit_required",
                ]
            ],
            use_container_width=True,
        )
    else:
        st.warning("No graph node data found.")

# ---------------------------------------------------------------------------
# 3. Redundant Path Analysis
# ---------------------------------------------------------------------------
with tabs[2]:
    st.subheader("Redundant Path Analysis")
    st.caption("Detected by walking each UserInput -> FinalAnswer path and tracking repeated guardrail keys.")

    if not redundant_df.empty:
        colf1, colf2, colf3 = st.columns(3)
        wf_filter = colf1.multiselect(
            "workflow_id",
            sorted(redundant_df["workflow_id"].unique()),
            key="redundant_path_workflow_id_filter",
        )
        gtype_filter = colf2.multiselect(
            "guardrail_type",
            sorted(redundant_df["guardrail_type"].unique()),
            key="redundant_path_guardrail_type_filter",
        )
        decision_filter = colf3.multiselect(
            "recommended_decision",
            sorted(redundant_df["recommended_decision"].unique()),
            key="redundant_path_recommended_decision_filter",
        )
        blocked_filter = st.multiselect(
            "blocked_by",
            sorted({b for s in redundant_df["blocked_by"].dropna() for b in s.split(";") if b}),
            key="redundant_path_blocked_by_filter",
        )

        filtered = redundant_df.copy()
        if wf_filter:
            filtered = filtered[filtered["workflow_id"].isin(wf_filter)]
        if gtype_filter:
            filtered = filtered[filtered["guardrail_type"].isin(gtype_filter)]
        if decision_filter:
            filtered = filtered[filtered["recommended_decision"].isin(decision_filter)]
        if blocked_filter:
            filtered = filtered[filtered["blocked_by"].apply(lambda s: any(b in str(s) for b in blocked_filter))]

        st.dataframe(filtered, use_container_width=True, height=450)
    else:
        st.info("No redundant paths detected in this run.")

# ---------------------------------------------------------------------------
# 4. Optimized Guardrail Plan
# ---------------------------------------------------------------------------
with tabs[3]:
    st.subheader("Optimized Guardrail Plan")

    colf1, colf2, colf3, colf4 = st.columns(4)
    decision_filter = colf1.multiselect(
        "recommended_decision",
        sorted(plan_df["recommended_decision"].unique()),
        key="optimized_plan_recommended_decision_filter",
    )
    boundary_filter = colf2.multiselect(
        "trust_boundary",
        sorted(plan_df["trust_boundary"].unique()),
        key="optimized_plan_trust_boundary_filter",
    )
    risk_filter = colf3.multiselect(
        "risk_level",
        sorted(plan_df["risk_level"].dropna().unique()),
        key="optimized_plan_risk_level_filter",
    )
    gtype_filter2 = colf4.multiselect(
        "guardrail_type",
        sorted(plan_df["guardrail_type"].dropna().unique()),
        key="optimized_plan_guardrail_type_filter",
    )

    filtered_plan = plan_df.copy()
    if decision_filter:
        filtered_plan = filtered_plan[filtered_plan["recommended_decision"].isin(decision_filter)]
    if boundary_filter:
        filtered_plan = filtered_plan[filtered_plan["trust_boundary"].isin(boundary_filter)]
    if risk_filter:
        filtered_plan = filtered_plan[filtered_plan["risk_level"].isin(risk_filter)]
    if gtype_filter2:
        filtered_plan = filtered_plan[filtered_plan["guardrail_type"].isin(gtype_filter2)]

    st.dataframe(filtered_plan, use_container_width=True, height=500)

# ---------------------------------------------------------------------------
# 5. Boundary Coverage Matrix
# ---------------------------------------------------------------------------
with tabs[4]:
    st.subheader("Boundary Coverage Matrix")
    if not boundary_df.empty:
        st.dataframe(boundary_df, use_container_width=True)
        protected = {"USER_TO_AGENT", "AGENT_TO_TOOL", "TOOL_TO_AGENT", "AGENT_TO_FINAL_RESPONSE"}
        protected_rows = boundary_df[boundary_df["trust_boundary"].isin(protected)]
        if (protected_rows["coverage_percent"] == 100.0).all():
            st.success("All protected trust boundaries remain at 100% coverage.")
        else:
            st.error("A protected trust boundary is below 100% coverage -- this should never happen.")
    else:
        st.info("No boundary coverage data found.")

# ---------------------------------------------------------------------------
# 6. Graph Risk Summary
# ---------------------------------------------------------------------------
with tabs[5]:
    st.subheader("Graph Risk Summary")
    if not summary_df.empty:
        top10 = summary_df.sort_values("graph_risk_score", ascending=False).head(10)
        st.dataframe(
            top10[
                [
                    "workflow_id",
                    "node_count",
                    "edge_count",
                    "redundant_internal_checks",
                    "missing_final_boundary_check",
                    "graph_risk_score",
                ]
            ],
            use_container_width=True,
        )
        st.bar_chart(top10.set_index("workflow_id")["graph_risk_score"])
    else:
        st.info("No workflow graph summary data found.")

# ---------------------------------------------------------------------------
# 7. Explanation Cards
# ---------------------------------------------------------------------------
with tabs[6]:
    st.subheader("Explanation Cards")
    st.caption("Plain-language, audit-friendly reasoning for the highest-impact workflows.")
    if explanations:
        for exp in explanations[:15]:
            with st.expander(f"{exp['workflow_id']} -- {exp['recommended_action']}"):
                st.write(exp["safety_reasoning"])
                st.markdown(f"**Duplicate pattern:** {exp['duplicate_guardrail_pattern']}")
                st.markdown(f"**Boundaries preserved:** {', '.join(exp['boundary_checks_preserved']) or 'none'}")
                st.markdown(f"**Latency saved:** {exp['latency_saved_ms']} ms")
                st.markdown(f"**Cost saved:** ${exp['cost_saved_usd']}")
                st.markdown(f"**Audit required:** {exp['audit_required']}")
                st.markdown(f"**Human review required:** {exp['human_review_required']}")
    else:
        st.info("No explanations generated for this run.")
