"""
run_pipeline.py
----------------
End-to-end pipeline for the Bedrock Guardrail Graph Optimizer.

    python src/run_pipeline.py
    python src/run_pipeline.py --workflows 500 --seed 42
    python src/run_pipeline.py --workflows 500 --strict-mode
    python src/run_pipeline.py --scenario healthcare_triage --workflows 20
    python src/run_pipeline.py --workflows 10000 --verbose

This is a Bedrock-style SIMULATION. It does not call live Amazon Bedrock
Guardrails or AgentCore Policy APIs. All numbers below are derived from
synthetic workflow traces generated by synthetic_workflows.py.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import time
from typing import Literal, Optional

from synthetic_workflows import save_synthetic_workflows, SCENARIOS
from graph_builder import build_all_workflow_graphs, save_graph_tables
from graph_features import save_workflow_graph_summary
from graph_optimizer import load_policy, detect_redundant_paths, generate_optimized_plan
from graph_metrics import compute_metrics, compute_boundary_coverage_matrix, compute_scenario_metrics
from explanations import generate_explanations
from schemas import validate_trace_df, validate_plan_df, validate_redundant_paths_df, SchemaValidationError

import pandas as pd

logger = logging.getLogger("guardrail_optimizer")


def _configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )


def _ensure_dirs() -> None:
    os.makedirs("data", exist_ok=True)
    os.makedirs("outputs", exist_ok=True)


class _StageTimer:
    """Context manager that logs a stage's start, and its wall-clock
    duration on exit -- gives a reviewer running with --verbose visibility
    into graph construction -> path enumeration -> decision counts per
    stage without instrumenting every call site by hand.
    """

    def __init__(self, name: str) -> None:
        self.name = name
        self.start: Optional[float] = None

    def __enter__(self) -> "_StageTimer":
        self.start = time.perf_counter()
        logger.info("Starting stage: %s", self.name)
        return self

    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> Literal[False]:
        assert self.start is not None
        elapsed = time.perf_counter() - self.start
        if exc_type is None:
            logger.info("Finished stage: %s (%.2fs)", self.name, elapsed)
        else:
            logger.error("Stage failed: %s (%.2fs)", self.name, elapsed)
        return False


def run(
    n_workflows: int = 420,
    seed: int = 42,
    strict_mode: bool = False,
    scenario: Optional[str] = None,
    verbose: bool = False,
) -> dict:
    _configure_logging(verbose)
    _ensure_dirs()
    pipeline_start = time.perf_counter()

    policy = load_policy("config/guardrail_policy.yaml")

    with _StageTimer("generate synthetic workflows"):
        if scenario:
            logger.info("Scenario mode: '%s' (%s)", scenario, SCENARIOS[scenario]["description"])
        df = save_synthetic_workflows(
            "data/synthetic_workflow_traces.csv", n_workflows=n_workflows, seed=seed, scenario=scenario
        )
        validate_trace_df(df)
        logger.debug("Generated %d rows across %d workflows.", len(df), df["workflow_id"].nunique())

    with _StageTimer("build workflow graphs"):
        graphs = build_all_workflow_graphs(df)
        save_graph_tables(graphs, "outputs/graph_nodes.csv", "outputs/graph_edges.csv")
        nodes_df = pd.read_csv("outputs/graph_nodes.csv")
        edges_df = pd.read_csv("outputs/graph_edges.csv")
        logger.debug("Built %d graphs, %d nodes, %d edges.", len(graphs), len(nodes_df), len(edges_df))

    with _StageTimer("compute graph-level features"):
        feature_df = save_workflow_graph_summary(
            graphs, policy.get("risk_score_weights", {}), "outputs/workflow_graph_summary.csv"
        )

    with _StageTimer("detect redundant guardrail paths (graph-path-aware)"):
        redundant_df = detect_redundant_paths(graphs, policy)
        redundant_df.to_csv("outputs/redundant_paths.csv", index=False)
        if not redundant_df.empty:
            validate_redundant_paths_df(redundant_df)
        logger.debug("Detected %d redundant path entries.", len(redundant_df))

    with _StageTimer("run graph-based guardrail placement optimizer"):
        plan_df = generate_optimized_plan(graphs, policy, strict_mode=strict_mode)
        validate_plan_df(plan_df)
        plan_df.to_csv("outputs/optimized_guardrail_plan.csv", index=False)
        decision_counts = plan_df["recommended_decision"].value_counts().to_dict()
        logger.debug("Decision counts: %s", decision_counts)

    with _StageTimer("compute metrics"):
        metrics = compute_metrics(df, graphs, plan_df, feature_df, policy)
        with open("outputs/guardrail_metrics.json", "w") as f:
            json.dump(metrics, f, indent=2)

        boundary_matrix = compute_boundary_coverage_matrix(plan_df, df, policy)
        boundary_matrix.to_csv("outputs/boundary_coverage_matrix.csv", index=False)

        scenario_metrics_df = compute_scenario_metrics(df, plan_df, policy)
        scenario_metrics_df.to_csv("outputs/scenario_metrics.csv", index=False)

    with _StageTimer("generate explanations"):
        explanations = generate_explanations(plan_df, graphs)
        with open("outputs/guardrail_explanations.json", "w") as f:
            json.dump(explanations, f, indent=2)

    total_elapsed = time.perf_counter() - pipeline_start

    # ---------------- Clean terminal summary ----------------
    overall = metrics["overall"]
    graph_m = metrics["graph"]
    safety = metrics["safety"]

    print("")
    print(f"Generated workflows: {df['workflow_id'].nunique()}")
    print(f"Graph nodes: {len(nodes_df):,}")
    print(f"Graph edges: {len(edges_df):,}")
    print(f"Original guardrail calls: {overall['original_guardrail_calls']:,}")
    print(f"Optimized guardrail calls: {overall['optimized_guardrail_calls']:,}")
    print(f"Guardrail call reduction: {overall['guardrail_call_reduction_percent']}%")
    print(f"Latency saved: {overall['latency_saved_percent']}%")
    print(f"Estimated cost saved: {overall['cost_saved_percent']}%")
    print(f"Redundant graph paths detected: {len(redundant_df):,}")
    print(f"Redundant paths optimized: {graph_m['redundant_paths_optimized']:,}")
    print(f"Blocked by safety rules: {graph_m['redundant_paths_blocked_by_safety']:,}")
    print(f"Boundary coverage preserved: {safety['boundary_coverage_preserved_percent']}%")
    print(f"High-risk checks preserved: {safety['high_risk_preservation_percent']}%")
    print(f"Human review cases: {safety['human_review_count']:,}")
    print(f"Total wall-clock time: {total_elapsed:.2f}s")

    metrics["_wall_clock_seconds"] = round(total_elapsed, 3)
    return metrics


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the Bedrock Guardrail Graph Optimizer pipeline.")
    parser.add_argument("--workflows", type=int, default=420, help="Number of synthetic workflows to generate.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility.")
    parser.add_argument(
        "--strict-mode",
        action="store_true",
        help="Disable SKIP_REDUNDANT_WITH_AUDIT; allow only REUSE_PREVIOUS_DECISION, escalate the rest to human review.",
    )
    parser.add_argument(
        "--scenario",
        type=str,
        default=None,
        choices=sorted(SCENARIOS.keys()),
        help="Run only this named scenario archetype end-to-end instead of the default mixed corpus.",
    )
    parser.add_argument("--verbose", action="store_true", help="Enable DEBUG-level structured logging.")
    args = parser.parse_args()

    run(
        n_workflows=args.workflows,
        seed=args.seed,
        strict_mode=args.strict_mode,
        scenario=args.scenario,
        verbose=args.verbose,
    )
